/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.sami.backtochildhood;

/**
 *
 * @author As-Sami
 */
public class FirstPage extends javax.swing.JFrame {
    
    /**
     * Creates new form FirstPage
     */
    
    
    public FirstPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        StartGame = new javax.swing.JPanel();
        PlayButton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();
        GameMode = new javax.swing.JPanel();
        MakeABox = new javax.swing.JButton();
        TicTacToe = new javax.swing.JButton();
        Ludo = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        MakeABoxChooseGrid = new javax.swing.JPanel();
        Type1 = new javax.swing.JButton();
        Type2 = new javax.swing.JButton();
        Type3 = new javax.swing.JButton();
        BackgroundPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Back to Childhood");
        setBackground(new java.awt.Color(132, 9, 219));
        setBounds(new java.awt.Rectangle(0, 0, 800, 500));
        setMaximumSize(new java.awt.Dimension(800, 500));
        setMinimumSize(new java.awt.Dimension(800, 500));
        setSize(new java.awt.Dimension(800, 500));
        getContentPane().setLayout(null);

        StartGame.setBackground(new java.awt.Color(101, 7, 168));
        StartGame.setForeground(java.awt.Color.white);
        StartGame.setFocusable(false);
        StartGame.setFont(new java.awt.Font("Constantia", 0, 24)); // NOI18N
        StartGame.setPreferredSize(new java.awt.Dimension(500, 300));
        StartGame.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                StartGameKeyTyped(evt);
            }
        });

        PlayButton.setBackground(new java.awt.Color(183, 77, 225));
        PlayButton.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        PlayButton.setText("Play");
        PlayButton.setActionCommand("PlayButton");
        PlayButton.setBorder(null);
        PlayButton.setFocusable(false);
        PlayButton.setPreferredSize(new java.awt.Dimension(100, 50));
        PlayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayButtonActionPerformed(evt);
            }
        });

        ExitButton.setBackground(new java.awt.Color(183, 77, 225));
        ExitButton.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        ExitButton.setText("Exit");
        ExitButton.setActionCommand("PlayButton");
        ExitButton.setBorder(null);
        ExitButton.setFocusable(false);
        ExitButton.setPreferredSize(new java.awt.Dimension(100, 50));
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout StartGameLayout = new javax.swing.GroupLayout(StartGame);
        StartGame.setLayout(StartGameLayout);
        StartGameLayout.setHorizontalGroup(
            StartGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StartGameLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addGroup(StartGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PlayButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(150, Short.MAX_VALUE))
        );
        StartGameLayout.setVerticalGroup(
            StartGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StartGameLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(PlayButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        getContentPane().add(StartGame);
        StartGame.setBounds(150, 100, 500, 300);

        GameMode.setBackground(new java.awt.Color(101, 7, 168));
        GameMode.setForeground(java.awt.Color.white);
        GameMode.setFocusable(false);
        GameMode.setFont(new java.awt.Font("Constantia", 0, 24)); // NOI18N
        GameMode.setPreferredSize(new java.awt.Dimension(500, 300));
        GameMode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                GameModeKeyTyped(evt);
            }
        });

        MakeABox.setBackground(new java.awt.Color(183, 77, 225));
        MakeABox.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        MakeABox.setText("Make a box");
        MakeABox.setActionCommand("PlayButton");
        MakeABox.setBorder(null);
        MakeABox.setFocusable(false);
        MakeABox.setPreferredSize(new java.awt.Dimension(100, 50));
        MakeABox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MakeABoxActionPerformed(evt);
            }
        });

        TicTacToe.setBackground(new java.awt.Color(183, 77, 225));
        TicTacToe.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        TicTacToe.setText("Tic-tac-toe");
        TicTacToe.setActionCommand("PlayButton");
        TicTacToe.setBorder(null);
        TicTacToe.setFocusable(false);
        TicTacToe.setPreferredSize(new java.awt.Dimension(100, 50));
        TicTacToe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TicTacToeActionPerformed(evt);
            }
        });

        Ludo.setBackground(new java.awt.Color(183, 77, 225));
        Ludo.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        Ludo.setText("Ludo");
        Ludo.setActionCommand("PlayButton");
        Ludo.setBorder(null);
        Ludo.setFocusable(false);
        Ludo.setPreferredSize(new java.awt.Dimension(100, 50));
        Ludo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LudoActionPerformed(evt);
            }
        });

        BackButton.setBackground(new java.awt.Color(183, 77, 225));
        BackButton.setFont(new java.awt.Font("MV Boli", 1, 14)); // NOI18N
        BackButton.setText("Back");
        BackButton.setActionCommand("PlayButton");
        BackButton.setBorder(null);
        BackButton.setFocusable(false);
        BackButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BackButton.setMaximumSize(new java.awt.Dimension(20, 20));
        BackButton.setMinimumSize(new java.awt.Dimension(20, 20));
        BackButton.setPreferredSize(new java.awt.Dimension(100, 50));
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout GameModeLayout = new javax.swing.GroupLayout(GameMode);
        GameMode.setLayout(GameModeLayout);
        GameModeLayout.setHorizontalGroup(
            GameModeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GameModeLayout.createSequentialGroup()
                .addContainerGap(154, Short.MAX_VALUE)
                .addGroup(GameModeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(MakeABox, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TicTacToe, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ludo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(146, 146, 146))
            .addGroup(GameModeLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        GameModeLayout.setVerticalGroup(
            GameModeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GameModeLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MakeABox, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(TicTacToe, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(Ludo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        getContentPane().add(GameMode);
        GameMode.setBounds(150, 100, 500, 300);
        GameMode.setVisible(false);

        MakeABoxChooseGrid.setBackground(new java.awt.Color(101, 7, 168));
        MakeABoxChooseGrid.setForeground(java.awt.Color.white);
        MakeABoxChooseGrid.setFocusable(false);
        MakeABoxChooseGrid.setFont(new java.awt.Font("Constantia", 0, 24)); // NOI18N
        MakeABoxChooseGrid.setPreferredSize(new java.awt.Dimension(500, 300));

        Type1.setBackground(new java.awt.Color(183, 77, 225));
        Type1.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        Type1.setText("4 X 4");
        Type1.setActionCommand("PlayButton");
        Type1.setBorder(null);
        Type1.setFocusable(false);
        Type1.setPreferredSize(new java.awt.Dimension(100, 50));
        Type1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Type1ActionPerformed(evt);
            }
        });

        Type2.setBackground(new java.awt.Color(183, 77, 225));
        Type2.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        Type2.setText("6 X 8");
        Type2.setActionCommand("PlayButton");
        Type2.setBorder(null);
        Type2.setFocusable(false);
        Type2.setPreferredSize(new java.awt.Dimension(100, 50));
        Type2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Type2ActionPerformed(evt);
            }
        });

        Type3.setBackground(new java.awt.Color(183, 77, 225));
        Type3.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        Type3.setText("10 X 12");
        Type3.setActionCommand("PlayButton");
        Type3.setBorder(null);
        Type3.setFocusable(false);
        Type3.setPreferredSize(new java.awt.Dimension(100, 50));
        Type3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Type3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MakeABoxChooseGridLayout = new javax.swing.GroupLayout(MakeABoxChooseGrid);
        MakeABoxChooseGrid.setLayout(MakeABoxChooseGridLayout);
        MakeABoxChooseGridLayout.setHorizontalGroup(
            MakeABoxChooseGridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MakeABoxChooseGridLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addGroup(MakeABoxChooseGridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Type2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Type1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Type3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(150, Short.MAX_VALUE))
        );
        MakeABoxChooseGridLayout.setVerticalGroup(
            MakeABoxChooseGridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MakeABoxChooseGridLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(Type1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(Type2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(Type3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        getContentPane().add(MakeABoxChooseGrid);
        MakeABoxChooseGrid.setBounds(150, 100, 500, 300);
        MakeABoxChooseGrid.setVisible(false);

        BackgroundPanel.setBackground(new java.awt.Color(55, 4, 92));
        BackgroundPanel.setForeground(java.awt.Color.white);
        BackgroundPanel.setFocusable(false);
        BackgroundPanel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                BackgroundPanelKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout BackgroundPanelLayout = new javax.swing.GroupLayout(BackgroundPanel);
        BackgroundPanel.setLayout(BackgroundPanelLayout);
        BackgroundPanelLayout.setHorizontalGroup(
            BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        BackgroundPanelLayout.setVerticalGroup(
            BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        getContentPane().add(BackgroundPanel);
        BackgroundPanel.setBounds(0, 0, 800, 500);

        getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        System.out.println("Exit");
        System.exit(0);
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void PlayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlayButtonActionPerformed
        System.out.println("Play");
        StartGame.setVisible(false);
        GameMode.setVisible(true);
    }//GEN-LAST:event_PlayButtonActionPerformed

    private void MakeABoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MakeABoxActionPerformed
        System.out.println("Make a box");
        GameMode.setVisible(false);
        MakeABoxChooseGrid.setVisible(true);
    }//GEN-LAST:event_MakeABoxActionPerformed

    private void TicTacToeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TicTacToeActionPerformed
        System.out.println("Tic tac toe"); 
        GameMode.setVisible(false);
        
        dispose();
        new TicTacToe();
    }//GEN-LAST:event_TicTacToeActionPerformed

    private void LudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LudoActionPerformed
        System.out.println("Ludo");
        GameMode.setVisible(false);
    }//GEN-LAST:event_LudoActionPerformed

    private void Type1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Type1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Type1ActionPerformed

    private void Type2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Type2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Type2ActionPerformed

    private void Type3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Type3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Type3ActionPerformed

    private void StartGameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_StartGameKeyTyped
        System.out.println("tying");
    }//GEN-LAST:event_StartGameKeyTyped

    private void BackgroundPanelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BackgroundPanelKeyTyped
        System.out.println("Typing in outer panel");
    }//GEN-LAST:event_BackgroundPanelKeyTyped

    private void GameModeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_GameModeKeyTyped
        if( evt.getKeyCode() == 27 ){
            GameMode.setVisible(false);
            StartGame.setVisible(true);
        }
    }//GEN-LAST:event_GameModeKeyTyped

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        GameMode.setVisible(false);
        StartGame.setVisible(true);
    }//GEN-LAST:event_BackButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FirstPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FirstPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FirstPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FirstPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FirstPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JPanel BackgroundPanel;
    private javax.swing.JButton ExitButton;
    private javax.swing.JPanel GameMode;
    private javax.swing.JButton Ludo;
    private javax.swing.JButton MakeABox;
    private javax.swing.JPanel MakeABoxChooseGrid;
    private javax.swing.JButton PlayButton;
    private javax.swing.JPanel StartGame;
    private javax.swing.JButton TicTacToe;
    private javax.swing.JButton Type1;
    private javax.swing.JButton Type2;
    private javax.swing.JButton Type3;
    // End of variables declaration//GEN-END:variables
}
