/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.sami.backtochildhood;

/**
 *
 * @author As-Sami
 */
public class FirstPage extends javax.swing.JFrame {
    
    /**
     * Creates new form FirstPage
     */
    
    
    public FirstPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        StartGame = new javax.swing.JPanel();
        kButton1 = new com.k33ptoo.components.KButton();
        kButton2 = new com.k33ptoo.components.KButton();
        GameMode = new javax.swing.JPanel();
        MakeABoxButton = new com.k33ptoo.components.KButton();
        TicTacToeButton = new com.k33ptoo.components.KButton();
        LudoButton = new com.k33ptoo.components.KButton();
        BackFromGameMode = new com.k33ptoo.components.KButton();
        MakeABoxChooseGrid = new javax.swing.JPanel();
        Start4x4 = new com.k33ptoo.components.KButton();
        Start6x8 = new com.k33ptoo.components.KButton();
        Start10x12 = new com.k33ptoo.components.KButton();
        BackFromMakeABox = new com.k33ptoo.components.KButton();
        BackgroundPanel = new javax.swing.JPanel();
        kGradientPanel2 = new com.k33ptoo.components.KGradientPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Back to Childhood");
        setBackground(new java.awt.Color(132, 9, 219));
        setBounds(new java.awt.Rectangle(0, 0, 800, 500));
        setMaximumSize(new java.awt.Dimension(800, 500));
        setMinimumSize(new java.awt.Dimension(800, 500));
        setSize(new java.awt.Dimension(800, 500));
        getContentPane().setLayout(null);

        StartGame.setBackground(new java.awt.Color(101, 7, 168));
        StartGame.setForeground(java.awt.Color.white);
        StartGame.setFocusable(false);
        StartGame.setFont(new java.awt.Font("Constantia", 0, 24)); // NOI18N
        StartGame.setPreferredSize(new java.awt.Dimension(500, 300));
        StartGame.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                StartGameKeyTyped(evt);
            }
        });

        kButton1.setText("Play");
        kButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton1ActionPerformed(evt);
            }
        });

        kButton2.setText("Exit");
        kButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout StartGameLayout = new javax.swing.GroupLayout(StartGame);
        StartGame.setLayout(StartGameLayout);
        StartGameLayout.setHorizontalGroup(
            StartGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StartGameLayout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addGroup(StartGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(kButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(187, Short.MAX_VALUE))
        );
        StartGameLayout.setVerticalGroup(
            StartGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StartGameLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(kButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(kButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        getContentPane().add(StartGame);
        StartGame.setBounds(150, 100, 500, 300);

        GameMode.setBackground(new java.awt.Color(101, 7, 168));
        GameMode.setForeground(java.awt.Color.white);
        GameMode.setFocusable(false);
        GameMode.setFont(new java.awt.Font("Constantia", 0, 24)); // NOI18N
        GameMode.setPreferredSize(new java.awt.Dimension(500, 300));

        MakeABoxButton.setText("make a box");
        MakeABoxButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MakeABoxButtonActionPerformed(evt);
            }
        });

        TicTacToeButton.setText("tix tac toe");
        TicTacToeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TicTacToeButtonActionPerformed(evt);
            }
        });

        LudoButton.setText("Ludo");
        LudoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LudoButtonActionPerformed(evt);
            }
        });

        BackFromGameMode.setText("Back");
        BackFromGameMode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackFromGameModeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout GameModeLayout = new javax.swing.GroupLayout(GameMode);
        GameMode.setLayout(GameModeLayout);
        GameModeLayout.setHorizontalGroup(
            GameModeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GameModeLayout.createSequentialGroup()
                .addGroup(GameModeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GameModeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BackFromGameMode, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(GameModeLayout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addGroup(GameModeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TicTacToeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MakeABoxButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LudoButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        GameModeLayout.setVerticalGroup(
            GameModeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GameModeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BackFromGameMode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MakeABoxButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TicTacToeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LudoButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        getContentPane().add(GameMode);
        GameMode.setBounds(150, 100, 500, 300);
        GameMode.setVisible(false);

        MakeABoxChooseGrid.setBackground(new java.awt.Color(101, 7, 168));
        MakeABoxChooseGrid.setForeground(java.awt.Color.white);
        MakeABoxChooseGrid.setFocusable(false);
        MakeABoxChooseGrid.setFont(new java.awt.Font("Constantia", 0, 24)); // NOI18N
        MakeABoxChooseGrid.setPreferredSize(new java.awt.Dimension(500, 300));

        Start4x4.setText("4x4");
        Start4x4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Start4x4ActionPerformed(evt);
            }
        });

        Start6x8.setText("6x8");
        Start6x8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Start6x8ActionPerformed(evt);
            }
        });

        Start10x12.setText("10x12");
        Start10x12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Start10x12ActionPerformed(evt);
            }
        });

        BackFromMakeABox.setText("Back");
        BackFromMakeABox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackFromMakeABoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MakeABoxChooseGridLayout = new javax.swing.GroupLayout(MakeABoxChooseGrid);
        MakeABoxChooseGrid.setLayout(MakeABoxChooseGridLayout);
        MakeABoxChooseGridLayout.setHorizontalGroup(
            MakeABoxChooseGridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MakeABoxChooseGridLayout.createSequentialGroup()
                .addGroup(MakeABoxChooseGridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MakeABoxChooseGridLayout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addGroup(MakeABoxChooseGridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Start10x12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Start6x8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Start4x4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(MakeABoxChooseGridLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BackFromMakeABox, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(167, Short.MAX_VALUE))
        );
        MakeABoxChooseGridLayout.setVerticalGroup(
            MakeABoxChooseGridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MakeABoxChooseGridLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BackFromMakeABox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Start4x4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(Start6x8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(Start10x12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        getContentPane().add(MakeABoxChooseGrid);
        MakeABoxChooseGrid.setBounds(150, 100, 500, 300);
        MakeABoxChooseGrid.setVisible(false);

        BackgroundPanel.setBackground(new java.awt.Color(55, 4, 92));
        BackgroundPanel.setForeground(java.awt.Color.white);
        BackgroundPanel.setFocusable(false);
        BackgroundPanel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                BackgroundPanelKeyTyped(evt);
            }
        });

        kGradientPanel2.setkEndColor(new java.awt.Color(36, 36, 62));
        kGradientPanel2.setkStartColor(new java.awt.Color(15, 12, 41));

        javax.swing.GroupLayout kGradientPanel2Layout = new javax.swing.GroupLayout(kGradientPanel2);
        kGradientPanel2.setLayout(kGradientPanel2Layout);
        kGradientPanel2Layout.setHorizontalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        kGradientPanel2Layout.setVerticalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout BackgroundPanelLayout = new javax.swing.GroupLayout(BackgroundPanel);
        BackgroundPanel.setLayout(BackgroundPanelLayout);
        BackgroundPanelLayout.setHorizontalGroup(
            BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        BackgroundPanelLayout.setVerticalGroup(
            BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(BackgroundPanel);
        BackgroundPanel.setBounds(0, 0, 800, 500);

        getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void StartGameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_StartGameKeyTyped
        System.out.println("tying");
    }//GEN-LAST:event_StartGameKeyTyped

    private void BackgroundPanelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BackgroundPanelKeyTyped
        System.out.println("Typing in outer panel");
    }//GEN-LAST:event_BackgroundPanelKeyTyped

    private void kButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton2ActionPerformed
        System.out.println("Exit");
        System.exit(0);
    }//GEN-LAST:event_kButton2ActionPerformed

    private void kButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton1ActionPerformed
        System.out.println("Play");
        StartGame.setVisible(false);
        GameMode.setVisible(true);
    }//GEN-LAST:event_kButton1ActionPerformed

    private void LudoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LudoButtonActionPerformed
        System.out.println("Ludo");
        GameMode.setVisible(false);
        dispose();
        new SnakeLudo(2);
    }//GEN-LAST:event_LudoButtonActionPerformed

    private void TicTacToeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TicTacToeButtonActionPerformed
        System.out.println("Tic tac toe"); 
        GameMode.setVisible(false);
        
        dispose();
        new TicTacToe();
    }//GEN-LAST:event_TicTacToeButtonActionPerformed

    private void MakeABoxButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MakeABoxButtonActionPerformed
        System.out.println("Make a box");
        GameMode.setVisible(false);
        MakeABoxChooseGrid.setVisible(true);
    }//GEN-LAST:event_MakeABoxButtonActionPerformed

    private void BackFromGameModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackFromGameModeActionPerformed
        GameMode.setVisible(false);
        StartGame.setVisible(true);
    }//GEN-LAST:event_BackFromGameModeActionPerformed

    private void Start4x4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Start4x4ActionPerformed
        MakeABoxChooseGrid.setVisible(false);
        dispose();
        new MakeABox(4,4);
    }//GEN-LAST:event_Start4x4ActionPerformed

    private void Start6x8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Start6x8ActionPerformed
        MakeABoxChooseGrid.setVisible(false);
        dispose();
        new MakeABox(6,8);
    }//GEN-LAST:event_Start6x8ActionPerformed

    private void Start10x12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Start10x12ActionPerformed
        MakeABoxChooseGrid.setVisible(false);
        dispose();
        new MakeABox(10,12);
    }//GEN-LAST:event_Start10x12ActionPerformed

    private void BackFromMakeABoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackFromMakeABoxActionPerformed
        MakeABoxChooseGrid.setVisible(false);
        GameMode.setVisible(true);
    }//GEN-LAST:event_BackFromMakeABoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FirstPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FirstPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FirstPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FirstPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FirstPage().setVisible(true);
            }
        });
    }
    
    void run(){
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FirstPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FirstPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FirstPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FirstPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FirstPage().setVisible(true);
            }
        });
    }
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton BackFromGameMode;
    private com.k33ptoo.components.KButton BackFromMakeABox;
    private javax.swing.JPanel BackgroundPanel;
    private javax.swing.JPanel GameMode;
    private com.k33ptoo.components.KButton LudoButton;
    private com.k33ptoo.components.KButton MakeABoxButton;
    private javax.swing.JPanel MakeABoxChooseGrid;
    private com.k33ptoo.components.KButton Start10x12;
    private com.k33ptoo.components.KButton Start4x4;
    private com.k33ptoo.components.KButton Start6x8;
    private javax.swing.JPanel StartGame;
    private com.k33ptoo.components.KButton TicTacToeButton;
    private com.k33ptoo.components.KButton kButton1;
    private com.k33ptoo.components.KButton kButton2;
    private com.k33ptoo.components.KGradientPanel kGradientPanel2;
    // End of variables declaration//GEN-END:variables
}
