/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.sami.backtochildhood;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author As-Sami
 */
public class FirstPage extends javax.swing.JFrame {
    
    /**
     * Creates new form FirstPage
     */
    private String gameName = "", username = "";
    
    public FirstPage() {
        initComponents();
    }
    
    public FirstPage(String username) {
        this.username = username;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        StartGame = new javax.swing.JPanel();
        kButton1 = new com.k33ptoo.components.KButton();
        kButton2 = new com.k33ptoo.components.KButton();
        GameMode = new javax.swing.JPanel();
        MakeABoxButton = new com.k33ptoo.components.KButton();
        TicTacToeButton = new com.k33ptoo.components.KButton();
        LudoButton = new com.k33ptoo.components.KButton();
        ChurPoliceButton = new com.k33ptoo.components.KButton();
        BackFromGameMode = new com.k33ptoo.components.KButton();
        MakeABoxChooseGrid = new javax.swing.JPanel();
        Start4x4 = new com.k33ptoo.components.KButton();
        Start6x8 = new com.k33ptoo.components.KButton();
        Start10x12 = new com.k33ptoo.components.KButton();
        BackFromMakeABox = new com.k33ptoo.components.KButton();
        MakeABoxChoose = new javax.swing.JPanel();
        OnlineButton1 = new com.k33ptoo.components.KButton();
        OfflineButton1 = new com.k33ptoo.components.KButton();
        Online = new javax.swing.JPanel();
        usernameJField = new javax.swing.JTextField();
        StartButton = new com.k33ptoo.components.KButton();
        TicTacToeChoose = new javax.swing.JPanel();
        OnlineButton = new com.k33ptoo.components.KButton();
        OfflineButton = new com.k33ptoo.components.KButton();
        SearchingPlayers = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BackgroundPanel = new javax.swing.JPanel();
        kGradientPanel2 = new com.k33ptoo.components.KGradientPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Back to Childhood");
        setBackground(new java.awt.Color(132, 9, 219));
        setBounds(new java.awt.Rectangle(0, 0, 800, 500));
        setMaximumSize(new java.awt.Dimension(800, 500));
        setMinimumSize(new java.awt.Dimension(800, 500));
        setSize(new java.awt.Dimension(800, 500));
        getContentPane().setLayout(null);

        StartGame.setBackground(new java.awt.Color(101, 7, 168));
        StartGame.setForeground(java.awt.Color.white);
        StartGame.setFocusable(false);
        StartGame.setFont(new java.awt.Font("Constantia", 0, 24)); // NOI18N
        StartGame.setPreferredSize(new java.awt.Dimension(500, 300));
        StartGame.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                StartGameKeyTyped(evt);
            }
        });

        kButton1.setText("Play");
        kButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton1ActionPerformed(evt);
            }
        });

        kButton2.setText("Exit");
        kButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout StartGameLayout = new javax.swing.GroupLayout(StartGame);
        StartGame.setLayout(StartGameLayout);
        StartGameLayout.setHorizontalGroup(
            StartGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StartGameLayout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addGroup(StartGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(kButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(187, Short.MAX_VALUE))
        );
        StartGameLayout.setVerticalGroup(
            StartGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StartGameLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(kButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(kButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        getContentPane().add(StartGame);
        StartGame.setBounds(150, 100, 500, 300);

        GameMode.setBackground(new java.awt.Color(101, 7, 168));
        GameMode.setForeground(java.awt.Color.white);
        GameMode.setFocusable(false);
        GameMode.setFont(new java.awt.Font("Constantia", 0, 24)); // NOI18N
        GameMode.setPreferredSize(new java.awt.Dimension(500, 300));

        MakeABoxButton.setText("make a box");
        MakeABoxButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MakeABoxButtonActionPerformed(evt);
            }
        });

        TicTacToeButton.setText("tix tac toe");
        TicTacToeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TicTacToeButtonActionPerformed(evt);
            }
        });

        LudoButton.setText("Ludo");
        LudoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LudoButtonActionPerformed(evt);
            }
        });

        ChurPoliceButton.setText("Chur Police");
        ChurPoliceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChurPoliceButtonActionPerformed(evt);
            }
        });

        BackFromGameMode.setText("Back");
        BackFromGameMode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackFromGameModeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout GameModeLayout = new javax.swing.GroupLayout(GameMode);
        GameMode.setLayout(GameModeLayout);
        GameModeLayout.setHorizontalGroup(
            GameModeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GameModeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BackFromGameMode, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addGroup(GameModeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LudoButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TicTacToeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MakeABoxButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ChurPoliceButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(155, Short.MAX_VALUE))
        );
        GameModeLayout.setVerticalGroup(
            GameModeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GameModeLayout.createSequentialGroup()
                .addGroup(GameModeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GameModeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BackFromGameMode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(GameModeLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(MakeABoxButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TicTacToeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LudoButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ChurPoliceButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        getContentPane().add(GameMode);
        GameMode.setBounds(150, 100, 500, 300);
        GameMode.setVisible(false);

        MakeABoxChooseGrid.setBackground(new java.awt.Color(101, 7, 168));
        MakeABoxChooseGrid.setForeground(java.awt.Color.white);
        MakeABoxChooseGrid.setFocusable(false);
        MakeABoxChooseGrid.setFont(new java.awt.Font("Constantia", 0, 24)); // NOI18N
        MakeABoxChooseGrid.setPreferredSize(new java.awt.Dimension(500, 300));

        Start4x4.setText("4x4");
        Start4x4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Start4x4ActionPerformed(evt);
            }
        });

        Start6x8.setText("6x8");
        Start6x8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Start6x8ActionPerformed(evt);
            }
        });

        Start10x12.setText("10x12");
        Start10x12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Start10x12ActionPerformed(evt);
            }
        });

        BackFromMakeABox.setText("Back");
        BackFromMakeABox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackFromMakeABoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MakeABoxChooseGridLayout = new javax.swing.GroupLayout(MakeABoxChooseGrid);
        MakeABoxChooseGrid.setLayout(MakeABoxChooseGridLayout);
        MakeABoxChooseGridLayout.setHorizontalGroup(
            MakeABoxChooseGridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MakeABoxChooseGridLayout.createSequentialGroup()
                .addGroup(MakeABoxChooseGridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MakeABoxChooseGridLayout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addGroup(MakeABoxChooseGridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Start10x12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Start6x8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Start4x4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(MakeABoxChooseGridLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BackFromMakeABox, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(167, Short.MAX_VALUE))
        );
        MakeABoxChooseGridLayout.setVerticalGroup(
            MakeABoxChooseGridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MakeABoxChooseGridLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BackFromMakeABox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Start4x4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(Start6x8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(Start10x12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        getContentPane().add(MakeABoxChooseGrid);
        MakeABoxChooseGrid.setBounds(150, 100, 500, 300);
        MakeABoxChooseGrid.setVisible(false);

        MakeABoxChoose.setBackground(new java.awt.Color(101, 7, 168));
        MakeABoxChoose.setForeground(java.awt.Color.white);
        MakeABoxChoose.setFocusable(false);
        MakeABoxChoose.setFont(new java.awt.Font("Constantia", 0, 24)); // NOI18N
        MakeABoxChoose.setPreferredSize(new java.awt.Dimension(500, 300));
        MakeABoxChoose.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                MakeABoxChooseKeyTyped(evt);
            }
        });

        OnlineButton1.setText("Online");
        OnlineButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OnlineButton1ActionPerformed(evt);
            }
        });

        OfflineButton1.setText("Offline");
        OfflineButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OfflineButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MakeABoxChooseLayout = new javax.swing.GroupLayout(MakeABoxChoose);
        MakeABoxChoose.setLayout(MakeABoxChooseLayout);
        MakeABoxChooseLayout.setHorizontalGroup(
            MakeABoxChooseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MakeABoxChooseLayout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addGroup(MakeABoxChooseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(OfflineButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OnlineButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(135, Short.MAX_VALUE))
        );
        MakeABoxChooseLayout.setVerticalGroup(
            MakeABoxChooseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MakeABoxChooseLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(OnlineButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(OfflineButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        getContentPane().add(MakeABoxChoose);
        MakeABoxChoose.setBounds(150, 100, 500, 300);
        MakeABoxChoose.setVisible(false);

        Online.setBackground(new java.awt.Color(101, 7, 168));
        Online.setForeground(java.awt.Color.white);
        Online.setFocusable(false);
        Online.setFont(new java.awt.Font("Constantia", 0, 24)); // NOI18N
        Online.setPreferredSize(new java.awt.Dimension(500, 300));
        Online.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                OnlineKeyTyped(evt);
            }
        });

        usernameJField.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        usernameJField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        usernameJField.setText("username");
        usernameJField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameJFieldActionPerformed(evt);
            }
        });

        StartButton.setText("Start");
        StartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout OnlineLayout = new javax.swing.GroupLayout(Online);
        Online.setLayout(OnlineLayout);
        OnlineLayout.setHorizontalGroup(
            OnlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OnlineLayout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addGroup(OnlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(StartButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(usernameJField))
                .addContainerGap(167, Short.MAX_VALUE))
        );
        OnlineLayout.setVerticalGroup(
            OnlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OnlineLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(usernameJField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(StartButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        getContentPane().add(Online);
        Online.setBounds(150, 100, 500, 300);
        Online.setVisible(false);

        TicTacToeChoose.setBackground(new java.awt.Color(101, 7, 168));
        TicTacToeChoose.setForeground(java.awt.Color.white);
        TicTacToeChoose.setFocusable(false);
        TicTacToeChoose.setFont(new java.awt.Font("Constantia", 0, 24)); // NOI18N
        TicTacToeChoose.setPreferredSize(new java.awt.Dimension(500, 300));
        TicTacToeChoose.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TicTacToeChooseKeyTyped(evt);
            }
        });

        OnlineButton.setText("Online");
        OnlineButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OnlineButtonActionPerformed(evt);
            }
        });

        OfflineButton.setText("Offline");
        OfflineButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OfflineButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TicTacToeChooseLayout = new javax.swing.GroupLayout(TicTacToeChoose);
        TicTacToeChoose.setLayout(TicTacToeChooseLayout);
        TicTacToeChooseLayout.setHorizontalGroup(
            TicTacToeChooseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TicTacToeChooseLayout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addGroup(TicTacToeChooseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(OfflineButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OnlineButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(135, Short.MAX_VALUE))
        );
        TicTacToeChooseLayout.setVerticalGroup(
            TicTacToeChooseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TicTacToeChooseLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(OnlineButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(OfflineButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        getContentPane().add(TicTacToeChoose);
        TicTacToeChoose.setBounds(150, 100, 500, 300);
        TicTacToeChoose.setVisible(false);

        SearchingPlayers.setBackground(new java.awt.Color(101, 7, 168));
        SearchingPlayers.setForeground(java.awt.Color.white);
        SearchingPlayers.setFocusable(false);
        SearchingPlayers.setFont(new java.awt.Font("Constantia", 0, 24)); // NOI18N
        SearchingPlayers.setPreferredSize(new java.awt.Dimension(500, 300));
        SearchingPlayers.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                SearchingPlayersKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Searching for players");
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        javax.swing.GroupLayout SearchingPlayersLayout = new javax.swing.GroupLayout(SearchingPlayers);
        SearchingPlayers.setLayout(SearchingPlayersLayout);
        SearchingPlayersLayout.setHorizontalGroup(
            SearchingPlayersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchingPlayersLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );
        SearchingPlayersLayout.setVerticalGroup(
            SearchingPlayersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SearchingPlayersLayout.createSequentialGroup()
                .addContainerGap(106, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106))
        );

        getContentPane().add(SearchingPlayers);
        SearchingPlayers.setBounds(150, 100, 500, 300);
        SearchingPlayers.setVisible(false);

        BackgroundPanel.setBackground(new java.awt.Color(55, 4, 92));
        BackgroundPanel.setForeground(java.awt.Color.white);
        BackgroundPanel.setFocusable(false);
        BackgroundPanel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                BackgroundPanelKeyTyped(evt);
            }
        });

        kGradientPanel2.setkEndColor(new java.awt.Color(36, 36, 62));
        kGradientPanel2.setkStartColor(new java.awt.Color(15, 12, 41));

        javax.swing.GroupLayout kGradientPanel2Layout = new javax.swing.GroupLayout(kGradientPanel2);
        kGradientPanel2.setLayout(kGradientPanel2Layout);
        kGradientPanel2Layout.setHorizontalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        kGradientPanel2Layout.setVerticalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout BackgroundPanelLayout = new javax.swing.GroupLayout(BackgroundPanel);
        BackgroundPanel.setLayout(BackgroundPanelLayout);
        BackgroundPanelLayout.setHorizontalGroup(
            BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        BackgroundPanelLayout.setVerticalGroup(
            BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(BackgroundPanel);
        BackgroundPanel.setBounds(0, 0, 800, 500);

        getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void StartGameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_StartGameKeyTyped
        System.out.println("tying");
    }//GEN-LAST:event_StartGameKeyTyped

    private void BackgroundPanelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BackgroundPanelKeyTyped
        System.out.println("Typing in outer panel");
    }//GEN-LAST:event_BackgroundPanelKeyTyped

    private void kButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton2ActionPerformed
        System.out.println("Exit");
        System.exit(0);
    }//GEN-LAST:event_kButton2ActionPerformed

    private void kButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton1ActionPerformed
        System.out.println("Play");
        StartGame.setVisible(false);
        GameMode.setVisible(true);
    }//GEN-LAST:event_kButton1ActionPerformed

    private void LudoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LudoButtonActionPerformed
        System.out.println("Ludo");
        GameMode.setVisible(false);
        dispose();
        new SnakeLudo(2);
    }//GEN-LAST:event_LudoButtonActionPerformed

    private void TicTacToeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TicTacToeButtonActionPerformed
        System.out.println("Tic tac toe"); 
        GameMode.setVisible(false);
        gameName = "tic-tac-toe";
        TicTacToeChoose.setVisible(true);
    }//GEN-LAST:event_TicTacToeButtonActionPerformed

    private void MakeABoxButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MakeABoxButtonActionPerformed
        System.out.println("Make a box");
        GameMode.setVisible(false);
        gameName = "make-a-box";
        MakeABoxChoose.setVisible(true);
    }//GEN-LAST:event_MakeABoxButtonActionPerformed

    private void BackFromGameModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackFromGameModeActionPerformed
        GameMode.setVisible(false);
        StartGame.setVisible(true);
    }//GEN-LAST:event_BackFromGameModeActionPerformed

    private void Start4x4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Start4x4ActionPerformed
        MakeABoxChooseGrid.setVisible(false);
        dispose();
         new MakeABox(4,4);
    }//GEN-LAST:event_Start4x4ActionPerformed

    private void Start6x8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Start6x8ActionPerformed
        MakeABoxChooseGrid.setVisible(false);
        dispose();
         new MakeABox(6,8);
    }//GEN-LAST:event_Start6x8ActionPerformed

    private void Start10x12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Start10x12ActionPerformed
        MakeABoxChooseGrid.setVisible(false);
        dispose();
         new MakeABox(10,12);
    }//GEN-LAST:event_Start10x12ActionPerformed

    private void BackFromMakeABoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackFromMakeABoxActionPerformed
        MakeABoxChooseGrid.setVisible(false);
        GameMode.setVisible(true);
    }//GEN-LAST:event_BackFromMakeABoxActionPerformed

    private void ChurPoliceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChurPoliceButtonActionPerformed
        GameMode.setVisible(false);
        gameName = "chur-police";
        Online.setVisible(true);
    }//GEN-LAST:event_ChurPoliceButtonActionPerformed

    private void OnlineKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_OnlineKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_OnlineKeyTyped

    private void StartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartButtonActionPerformed
        System.out.println("action in button");
        System.out.println(usernameJField.getText());
        Online.setVisible(false);
        SearchingPlayers.setVisible(true);
        
        repaint();
        System.out.println("Game :" + gameName);
        
        if(gameName=="tic-tac-toe"){
            try {
                TicTacToeMakeOnline.run(usernameJField.getText(), this);
            } catch (IOException ex) {
                System.out.println("error in online katakuti");
            }
        }else if( gameName=="make-a-box" ){
            try {
                MakeABoxMakeOnline.run(usernameJField.getText(), this);
            } catch (IOException ex) {
                Logger.getLogger(FirstPage.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else if( gameName=="chur-police" ){
            try {
                ChurPoliceMakeOnline.run(usernameJField.getText(), this);
            } catch (IOException ex) {
                Logger.getLogger(FirstPage.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_StartButtonActionPerformed

    private void usernameJFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameJFieldActionPerformed
        StartButton.doClick();
    }//GEN-LAST:event_usernameJFieldActionPerformed

    private void OnlineButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OnlineButtonActionPerformed
        TicTacToeChoose.setVisible(false);
        gameName = "tic-tac-toe";
        Online.setVisible(true);
    }//GEN-LAST:event_OnlineButtonActionPerformed

    private void OfflineButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OfflineButtonActionPerformed
        dispose();
        new TicTacToe();
    }//GEN-LAST:event_OfflineButtonActionPerformed

    private void TicTacToeChooseKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TicTacToeChooseKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_TicTacToeChooseKeyTyped

    private void SearchingPlayersKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SearchingPlayersKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchingPlayersKeyTyped

    private void OnlineButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OnlineButton1ActionPerformed
        MakeABoxChoose.setVisible(false);
        Online.setVisible(true);
    }//GEN-LAST:event_OnlineButton1ActionPerformed

    private void OfflineButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OfflineButton1ActionPerformed
        MakeABoxChoose.setVisible(false);
        MakeABoxChooseGrid.setVisible(true);
    }//GEN-LAST:event_OfflineButton1ActionPerformed

    private void MakeABoxChooseKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MakeABoxChooseKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_MakeABoxChooseKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FirstPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FirstPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FirstPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FirstPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FirstPage().setVisible(true);
            }
        });
    }
    
    void run(){
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FirstPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FirstPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FirstPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FirstPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FirstPage().setVisible(true);
            }
        });
    }
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton BackFromGameMode;
    private com.k33ptoo.components.KButton BackFromMakeABox;
    private javax.swing.JPanel BackgroundPanel;
    private com.k33ptoo.components.KButton ChurPoliceButton;
    private javax.swing.JPanel GameMode;
    private com.k33ptoo.components.KButton LudoButton;
    private com.k33ptoo.components.KButton MakeABoxButton;
    private javax.swing.JPanel MakeABoxChoose;
    private javax.swing.JPanel MakeABoxChooseGrid;
    private com.k33ptoo.components.KButton OfflineButton;
    private com.k33ptoo.components.KButton OfflineButton1;
    private javax.swing.JPanel Online;
    private com.k33ptoo.components.KButton OnlineButton;
    private com.k33ptoo.components.KButton OnlineButton1;
    private javax.swing.JPanel SearchingPlayers;
    private com.k33ptoo.components.KButton Start10x12;
    private com.k33ptoo.components.KButton Start4x4;
    private com.k33ptoo.components.KButton Start6x8;
    private com.k33ptoo.components.KButton StartButton;
    private javax.swing.JPanel StartGame;
    private com.k33ptoo.components.KButton TicTacToeButton;
    private javax.swing.JPanel TicTacToeChoose;
    private javax.swing.JLabel jLabel1;
    private com.k33ptoo.components.KButton kButton1;
    private com.k33ptoo.components.KButton kButton2;
    private com.k33ptoo.components.KGradientPanel kGradientPanel2;
    private javax.swing.JTextField usernameJField;
    // End of variables declaration//GEN-END:variables
}
